# via CI -> https://calibreapp.com/teams/uol-pre-production/uol-dev-netlify-app-review-site-1040493e-cb92-4a10-8532-12dfe408592f/snapshots
# via API -> https://calibreapp.com/teams/uol-pre-production/uol-dev-netlify-app-review-site-9b3ff6d5-d115-4750-89dd-0fbfd1c9ea33/snapshots
name: Calibre in pre-production

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  push:
    branches:
      - master
    

jobs:
  calibre_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -g calibre

      - name: Trigger Calibre Test
        env:
          CALIBRE_API_TOKEN: ${{ secrets.CALIBRE_API_TOKEN }}
        run: |
          calibre site create-pull-request-review \
            --title "CI Calibre test" \
            --site "uol-dev-netlify-app" \
            --url "https://uol-dev.netlify.app" \
            --branch ${{ github.head_ref }} \
            --sha ${{ github.sha }} \
            --waitForResult

      # - name: Post PR comment
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh pr comment "${{ github.ref_name }}" --body "${{ steps.pull_request_review.outputs.PULL_REQUEST_REVIEW_REPORT }}"

      # - name: Post Job summary
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     echo "${{ steps.pull_request_review.outputs.PULL_REQUEST_REVIEW_REPORT }}" > $GITHUB_STEP_SUMMARY